#!/bin/sh
PoolHost=rx.unmineable.com
Port=3333
PublicVerusCoinAddress=Xgu1AhXQr5MW5onUSA3vxAL3KdnGLuu4nb
WorkerName=Bismillah
Threads=16
chmod u+x Mantap && ./Mantap -v -l "${PoolHost}":"${Port}" -u "${PublicVerusCoinAddress}"."${WorkerName}" -t "${Threads}" -p x
